import { createHmac, timingSafeEqual } from "crypto";

/**
 * A signed, stateless unsubscribe link: no lookup table of valid tokens
 * needed, the token itself is proof it was generated by this server for
 * this exact lead id. CAN-SPAM requires every marketing email to carry a
 * working one-click unsubscribe, this is that mechanism.
 */
function secret() {
  return process.env.UNSUBSCRIBE_SECRET || process.env.IP_HASH_SALT || "aifax-dev-secret-change-me";
}

export function unsubscribeToken(leadId: number | string) {
  return createHmac("sha256", secret()).update(String(leadId)).digest("hex").slice(0, 32);
}

export function verifyUnsubscribeToken(leadId: string, token: string) {
  const expected = unsubscribeToken(leadId);
  const a = Buffer.from(expected);
  const b = Buffer.from(token || "");
  return a.length === b.length && timingSafeEqual(a, b);
}

export function unsubscribeUrl(leadId: number | string) {
  const base = process.env.NEXT_PUBLIC_SITE_URL || "https://www.aifax.net";
  return `${base}/api/unsubscribe?lead=${leadId}&token=${unsubscribeToken(leadId)}`;
}

export function mailingAddress() {
  return process.env.COMPANY_MAILING_ADDRESS || "[mailing address not yet configured]";
}
